version: '3'

services:
  web_server:
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - ./:/app

  web_server2:
    build: ./
    ports:
      - '8001:8000'
    volumes:
      - ./:/app

  web_server3:
    build: ./
    ports:
      - '8002:8000'
    volumes:
      - ./:/app

  db:
    image: postgres:9.6.2
    volumes:
      - storage:/var/lib/postgresql/data
    restart: "always"

volumes:
  storage:
